# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-06 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('brief', models.CharField(blank=True, max_length=255)),
                ('age', models.IntegerField(blank=True)),
                ('sex', models.IntegerField(choices=[(1, 'male'), (2, 'famale')], default=1)),
                ('email', models.EmailField(max_length=255)),
                ('head_img', models.ImageField(upload_to='head_img/%Y/%m/%d')),
                ('follow_list', models.ManyToManyField(blank=True, related_name='my_followers', to='app01.Acount')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Weibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wb_type', models.IntegerField(choices=[(0, 'new'), (1, 'forward'), (2, 'collect')], default=0)),
                ('text', models.CharField(max_length=140)),
                ('pictures_link_id', models.CharField(blank=True, max_length=128, null=True)),
                ('video_link_id', models.CharField(blank=True, max_length=128, null=True)),
                ('perm', models.IntegerField(choices=[(0, 'public'), (1, 'private'), (2, 'friends')], default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('forward_or_collect_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forward_or_collects', to='app01.Weibo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Acount')),
            ],
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='acount',
            name='tags',
            field=models.ManyToManyField(to='app01.Tags'),
        ),
        migrations.AddField(
            model_name='acount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.Weibo'),
        ),
    ]
