# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-06 07:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20170706_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acount',
            name='head_img',
            field=models.ImageField(default='', upload_to='head_img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='acount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
